### PR TITLE
Fixing QItemSelectionRange for #232

### PR DESCRIPTION
**Pull request by Ahuge**
This is a simple fix for #232 that just adds QItemSelectionRange

### CODE REVIEW

**Comment by Ahuge** [comment]
Looping in @RafeSacks just so he knows the status of this

**Comment by mottosso** [comment]
Looks good, thanks!

**Comment by Ahuge** [comment]
Awesome, any chance we could get a release beta for this?

**Comment by mottosso** [comment]
https://github.com/mottosso/Qt.py/releases/tag/1.1.0.b6

**Comment by Ahuge** [comment]
Thanks!

**Pull request merged**
