### PR TITLE
AppVeyor support

### PR DESCRIPTION
**Pull request by mottosso**
A.k.a. testing on Windows

### CODE REVIEW

**Comment by mottosso** [comment]
Once merged, we'll get a new set of errors regarding instantiating QApplication [here](https://github.com/mottosso/Qt.py/pull/81) without a graphics card plugged in.

Let me know if you spot anything off.

**Comment by fredrikaverpil** [comment]
This is awesome. I haven't dug through this yet, but so far it looks great.

**Comment by mottosso** [comment]
The important bit is what's in the `appveyor.yml` file, the rest is PEP08 and making it work on Windows.

As tests.py was modified, there's some merging to be done in your other PR, but there shouldn't be any conflicts.

**Comment by fredrikaverpil** [comment]
No problem, I'll rebase when this is merged. Merge away!

**Pull request merged**
