### PR TITLE
Feature/udemy course

### PR DESCRIPTION
**Pull request by fredrikaverpil**
Added a video link on Qt.py from Dhruv Govil's [Udemy course](https://www.udemy.com/python-for-maya/learn/v4/overview) to a new "Mentions" section in the README.

I also linked to his Github repo (with sample code using Qt.py) under "Projects using Qt.py".

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
@dgovil ping, nice work!

**Comment by mottosso** [comment]
LGTM!

**Comment by fredrikaverpil** [comment]
Merging!

**Comment by dgovil** [comment]
Thanks Frederik!

**Pull request merged**
