### PR TITLE
python2.6 support

### PR DESCRIPTION
**Pull request by Ahuge**
Working on #235 

Don't merge yet. I haven't had a change to do it all yet or run the unittests yet.

### CODE REVIEW

**Comment by Ahuge** [comment]
I don't know Travis well enough to setup 2.6 tests. Do we need/want them?

I think it would be somewhere in the docker setup that I would add support for 2.6 I think.

**Comment by fredrikaverpil** [comment]
> I don't know Travis well enough to setup 2.6 tests. Do we need/want them?

The question is whether all the bindings will build on Python 2.6... I'm not sure. I would have to try that. For this PR, I suggest we skip such a test for now. I can add Python 2.6 support the next time I'm working on the #234 and see what happens.

**Comment by Ahuge** [comment]
Hey so I fixed the houndci issues, I am changing the title of this to remove the "WIP"

**Comment by mottosso** [comment]
Completely missed this one, sorry about that. I think this looks good. @Ahuge would you happen to have tested this (in production)?

**Comment by Ahuge** [comment]
I think I've got a copy of it at work, I'll confirm in a bit

**Comment by Ahuge** [comment]
Yeah confirmed the branch py26-support works in production.

**Comment by fredrikaverpil** [comment]
I'd say let's just merge this then.

**Pull request merged**
