### PR TITLE
wrapInstance and getCppPointer 

### PR DESCRIPTION
**Pull request by dgovil**
Doing a merge of https://github.com/mottosso/Qt.py/pull/190 to the latest version of `Qt.py`

### CODE REVIEW

**Comment by dgovil** [comment]
I am unable to resolve these hound errors. The long name is being tripped up because long doesn't exist in Python3 and the indentation errors are because of the sources use of lambdas. I could unindent but I feel that looks worse?

**Comment by dgovil** [comment]
Lesson learned, Py2 has a different scoping system than Py3. Declaring long inside a function causes py2 to error. Has to be declared in the global scope.

Anyway tests are now passing. 

As for the remaining issues:
* Hound: I don't know how to address these indentation errors without affecting the line length or making it more unreadable. Thoughts?

* The license/cla test says I haven't signed it but when I click details it says I have (and I have for previous PR's so not sure why its failing)

**Comment by mottosso** [comment]
Hey @dgovil, there's something not right about this merge, it appears to merge another version than the latest. 

[Here's](https://github.com/abstractfactory/Qt.py/blob/ec26a563cccc291fe8ebc1d6002f14fb6bd2ab5f/Qt.py#L786) what the latest look like, where the wrapInstance line length issue has already been addressed, and [here's](https://github.com/dgovil/Qt.py/blob/7f0272f0cfb859ae956ed8f6588bf1322b27fa89/Qt.py#L752) what this merge looks like.

I also realised that I thought this was originally your PR, when it was actually I who made it. Sorry for asking you to do this merge for me, how lazy of me!

I finished up the original PR now and will release in a few mins.

**Comment by dgovil** [comment]
Odd not sure how it picked up the older version since I pulled latest. But glad you merged the original! thanks!

**Pull request closed without merging**
