### PR TITLE
Initial setup for travis

### PR DESCRIPTION
**Pull request by mottosso**

### CODE REVIEW

**Comment by mottosso** [comment]
Now we can setup up automated tests for the various bindings to make sure they work.

**Comment by fredrikaverpil** [comment]
Excellent, LGTM!

**Comment by mottosso** [comment]
It's a wip so far, doesn't do anything useful yet. It's just that I need to push to GitHub it to see what Travis will do. At the moment, it for some reason doesn't allow me to install PySide.

I'll be updating this PR many times until it works well.

**Comment by fredrikaverpil** [comment]
Ok, great!

> for some reason doesn't allow me to install PySide.

Sounds like the story of my life... 😿

**Comment by mottosso** [comment]
I don't know what happened.

**Pull request closed without merging**
