### PR TITLE
Revert "Provide Qt.load_ui"

### PR DESCRIPTION
**Pull request by mottosso**
Reverts mottosso/Qt.py#33

### CODE REVIEW

**Comment by mottosso** [comment]
Sorry, I think it obscures the overall code too much as it is now.

Could we remake this PR and talk more about how to make it shine?

**Comment by fredrikaverpil** [comment]
> Could we remake this PR 

Sure, let me know what you think we should do.

**Comment by mottosso** [comment]
Ok, sorry about that. I just haven't had the time to properly look at it yet. :(

There's a thing in git called "cherry picking". You can cherry pick your commit back onto the repo at this point in time, and then you can remake the PR. It'll basically be reverting the revert.

**Comment by fredrikaverpil** [comment]
Sure.

Maybe I'm just not used to PRs in github, but wouldn't it have been useful to just keep the PR pending?

**Comment by fredrikaverpil** [comment]
Or do you want me to resubmit the PR as-is now so you can review it?

**Comment by mottosso** [comment]
No worries! This is on me. I should've said I had trouble with it but didn't find the time to properly articulate it.

> Maybe I'm just not used to PRs in github, but wouldn't it have been useful to just keep the PR pending?

Yes, it would be good to keep PRs pending until we've both given a thumbs up. Not necessarily for smaller ones, but significant ones like this definitely.

Once you've remade your PR, we'll keep working on it until we're both happy, then we'll merge.

**Comment by fredrikaverpil** [comment]
Ok! 😄

**Pull request merged**
