### PR TITLE
Binding specific replacement mappings as a dictionary, similar to _common_members.

### PR DESCRIPTION
**Pull request by Ahuge**
This is a PR that aims to solve #211.

You can see in my first commit that I had been silently ignoring the missing modules, or setting dummy ones. Let me know if that is desired functionality, I doubt it is though.

### CODE REVIEW

**Comment by Ahuge** [comment]
Ack Travis has failed. Digging into now

**Comment by Ahuge** [comment]
Setting up docker locally for myself. I don't want to deal with installing all the bindings manually if I don't have to. 

I might not get to solving all the failed tests right now, might have to be in 18 hours or so.

**Comment by mottosso** [comment]
> I might not get to solving all the failed tests right now, might have to be in 18 hours or so.

Take your time @Ahug. Thanks for the effort.

**Comment by Ahuge** [comment]
Updated it but even on 67710d40265b9382d7abfc5b43b1822b199bf289 there appears to be 6 failing cases in my local docker environment.

I am pretty sure there is no test case regression on my part.

**Comment by Ahuge** [comment]
Had a small misstyping in my PySide2 bindings. Should be all good now, waiting on Travis

**Comment by mottosso** [comment]
Thanks @Ahuge! Having a look.

**Comment by mottosso** [comment]
About the `_setattr` and friends, I feel that add quite a bit of complexity to the benefit we're reaping here. 

Do you think we could get away with a plain `setattr` if we didn't have to deal with `QHeaderView.setResizeMode`? It looks like the dynamic nature of these functions could be reduced if we could assert that each replacement is accessing exactly one member of one submodule, e.g. `QHeaderView` of `QtWidgets`.

**Comment by Ahuge** [comment]
Yeah I agree about the complexity,

I will spin up a commit just going the one level deep in the morning and move setResizeMode back into the binding function.

Thanks

**Comment by mottosso** [comment]
I gave it a go, let me know what you think.

About QHeaderView and other more complex reassignments, there's a [sibling PR](https://github.com/mottosso/Qt.py/pull/210) about namespacing those members. I think that could go well with this simplification!

**Comment by Ahuge** [comment]
Cool yeah that looks great! Thanks for doing that. 

The sibling PR looks neat as well, I think it could help with the reassignments too. 

Thanks for being patient with me and for all your help

**Comment by fredrikaverpil** [comment]
I've been away for some time and are now looking through what I've missed... I just wanted to chime in and say this looks very neat. Very nicely done, @Ahuge @mottosso !

**Pull request merged**
