### PR TITLE
Binding State Enums

### PR DESCRIPTION
**Pull request by dgovil**
This adds flags to `Qt.py` that allow end users to check the binding more easily.
Rather  than comparing strings in every piece of code like so:

```python
if Qt.__binding__ == 'PySide2': doSomething()
```

They can now simply do

```python
if Qt.PYSIDE2: doSomething()
```

This in turn makes for less error prone code since string comparisons have the increased risks of typos not caught till runtime.

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks @dgovil, I'm no fan of this particular syntax.

How about this?

```python
if Qt.__binding__ == Qt.PYSIDE2:
  doSomething()
```

Or this?

```python
if Qt.IsPySide2:
  doSomething()

if Qt.ISPYSIDE2:
  doSomething()

if Qt.IS_PYSIDE2:
  doSomething()
```

**Comment by fredrikaverpil** [comment]
Hey this is nice @dgovil - thanks :)

I also think it is better to use prefixes somehow, as this is what Qt does to both functions and constants.

I believe the last time we discussed naming, we opted to follow the type of naming used throughout of Qt/PySide2. And if we were to follow that I would say it should be `Qt.isPySide2()` for a function or `Qt.IsPySide2` for a constant.

**Comment by dgovil** [comment]
So I've renamed them to be prefixed and camel cased them to be in line with the Qt functions.
I think that's cleaner.

**Comment by fredrikaverpil** [comment]
Nice!
This all looks great to me.

@mottosso what do you think?

**Comment by mottosso** [comment]
Sorry to be picky, but why is this a function? To me this has all the hallmarks of a constant, and constants in Qt are CamelCase. https://doc.qt.io/qt-5/qt.html

**Comment by dgovil** [comment]
That's fine. I can switch them to constants. Performance would be minorly
better too. I'll put an update in a couple hours when I'm back to my pc

**Comment by dgovil** [comment]
@mottosso, forgot to update the thread, but they're now using CamelCased
constant values

**Comment by mottosso** [comment]
I think it looks good! Real slick work with the one test for all four bindings. :) Thanks @dgovil!

**Pull request merged**
