### PR TITLE
Add CAVEATS.md

### PR DESCRIPTION
**Pull request by fredrikaverpil**
Here's a starting point for conversation regarding https://github.com/mottosso/Qt.py/issues/65 ...

- I didn't call the file `INCOMPATIBILITIES.md` because of the long file name.
- I first added the TOC in the `README.md` but realised users may expect a TOC inside of `CAVEATS.md` and I really didn't want it in both of them for maintenance purposes.

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
Markdown preview [here](https://github.com/fredrikaverpil/Qt.py/blob/feature/caveats/CAVEATS.md).

**Comment by mottosso** [comment]
Thanks, looks good. Not a big fan of how compressed it all is, finding it difficult to read. I'd add some breathing room between paragraphs and discard the top-level headers, e.g. `QtCore`.

**Comment by fredrikaverpil** [comment]
I've grown a bit used to this "in between paragraph spacing" behaviour... I don't know why this is the default everywhere. It's strange and it goes against everything I've learnt about typography and grid systems. But I guess I've learnt to just accept this and get in line with how e.g. Github wanted this to work.

Anyhow, I've added three `<br>` tags after each paragraph, like in the README. Also removed the top-levels.

Merge away if it looks good!

**Comment by fredrikaverpil** [comment]
I noticed some formatting mistakes. Fixed them now. Markdown preview [here](https://github.com/fredrikaverpil/Qt.py/blob/feature/caveats/CAVEATS.md).

**Comment by mottosso** [comment]
Looks good!

**Pull request merged**
