### PR TITLE
Implement #21

### PR DESCRIPTION
**Pull request by mottosso**
Not sure about PySide2 here, are you able to test, @fredrikaverpil?

### CODE REVIEW

**Comment by mottosso** [comment]
Also what do you think about camel_case instead of mixedCase? E.g. `__qt_version__` instead of `__qtVersion__`. Just feels wrong. All of these bindings are just wrong.

**Comment by fredrikaverpil** [comment]
> are you able to test

Yep, will do.

>  __qt_version__ instead of __qtVersion__

[PEP8 naming convention](https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions) doesn't say anything about variables, it seems. However, I generally do prefer lowercase with words separated by underscores.

**Comment by fredrikaverpil** [comment]
```python
import PySide2
print PySide2.__version__
>>> 2.0.0~alpha0
print PySide2.QtCore.qVersion()
>>> 5.6.0
```

**Comment by mottosso** [comment]
Awesome sauce

**Comment by fredrikaverpil** [comment]
Hey, how did you make those changes?
I need to learn how to do that.

**Comment by mottosso** [comment]
Any changes you make to your branch during a pull-request are automatically added to the pull request.

**Comment by fredrikaverpil** [comment]
Ah, that's really good to know.

**Pull request merged**
