### PR TITLE
fix bug #344

### PR DESCRIPTION
**Pull request by FXTD-ODYSSEY**
fix ui file using custom widget bug
https://github.com/mottosso/Qt.py/issues/344

### CODE REVIEW

**Comment by mottosso** [comment]
@FXTD-ODYSSEY Don't forget to click the CLA accept button, to transfer ownership of the change to the Qt.py project.

**Comment by FXTD-ODYSSEY** [comment]
Sorry for Interrupting.
This pull request seem to be ready @mottosso

**Comment by mottosso** [comment]
Yes! Sorry for missing this, thanks for the reminder and PR @FXTD-ODYSSEY!

**Comment by mottosso** [comment]
Released as 1.3.1

- https://github.com/mottosso/Qt.py/releases/tag/1.3.1

**Pull request merged**
